"""add externalid and ip yo session

Revision ID: 1c44f8ccfafb
Revises: 068d2ba2f0b8
Create Date: 2026-04-09 14:50:22.006021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c44f8ccfafb'
down_revision: Union[str, Sequence[str], None] = '068d2ba2f0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('externalId', sa.String(), nullable=True), schema='auth')
    op.create_unique_constraint(None, 'users', ['externalId'], schema='auth')
    op.add_column('users_sessions', sa.Column('ip', sa.String(), nullable=False), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_sessions', 'ip', schema='auth')
    op.drop_constraint(None, 'users', schema='auth', type_='unique')
    op.drop_column('users', 'externalId', schema='auth')
    # ### end Alembic commands ###
