"""primera_migracion

Revision ID: 39c4deb7cc1f
Revises: 
Create Date: 2026-03-17 14:08:37.297094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c4deb7cc1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Crear esquemas si no existen
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS reports")
    op.execute("CREATE SCHEMA IF NOT EXISTS points")
    op.execute("CREATE SCHEMA IF NOT EXISTS notifications")
    op.execute("CREATE SCHEMA IF NOT EXISTS logs")
    
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'tecnico', name='user_role'), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_table('notifications_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='notifications'
    )
    op.create_table('reason_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='points'
    )
    op.create_table('report_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='reports'
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='logs'
    )
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reasonId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reasonId'], ['points.reason_points.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='points'
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pendiente', 'en_revision', 'resuelto', name='report_status'), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('resolvedById', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'mid', 'high', name='report_priority'), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['reports.report_category.id'], ),
    sa.ForeignKeyConstraint(['resolvedById'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reports'
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('reportId', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=False),
    sa.Column('typeId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reportId'], ['reports.reports.id'], ),
    sa.ForeignKeyConstraint(['typeId'], ['notifications.notifications_type.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reportId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reportId'], ['reports.reports.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reports'
    )
    op.create_table('report_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reportId', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reportId'], ['reports.reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reports'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_images', schema='reports')
    op.drop_table('comments', schema='reports')
    op.drop_table('notifications', schema='notifications')
    op.drop_table('reports', schema='reports')
    op.drop_table('points', schema='points')
    op.drop_table('logs', schema='logs')
    op.drop_table('report_category', schema='reports')
    op.drop_table('reason_points', schema='points')
    op.drop_table('notifications_type', schema='notifications')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
